backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "src/content/artworks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Medium", name: "medium", widget: "string", required: false}
      - {label: "Date Added", name: "date", widget: "datetime"}